name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Flake 8 Syntax Errors
      run: |
        flake8 scripts lib backends --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Flake 8 Syntax Warnings
      run: | 
        flake8 lib scripts backends --exclude backends/fadecandy/opc.py --count --max-complexity=10 --max-line-length=127 --statistics --ignore E402
